//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 05:16:20 PM CST 
//


package com.wincom.actor.adaptor.messages;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


@XmlRootElement(name="components")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Components", propOrder = {
    "actorTypes"
})
public class Components {

    @XmlElement(name = "actor-types", required = true)
    protected ActorTypeList actorTypes = new ActorTypeList();

    /**
     * Gets the value of the actorTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ActorTypeList }
     *     
     */
    public ActorTypeList getActorTypes() {
        return actorTypes;
    }

    /**
     * Sets the value of the actorTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActorTypeList }
     *     
     */
    public void setActorTypes(ActorTypeList value) {
        this.actorTypes = value;
    }

}
