//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.22 at 05:56:16 PM CST 
//


package com.wincom.actor.adaptor.messages;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wincom.actor.adaptor.messages package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wincom.actor.adaptor.messages
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActorType }
     * 
     */
    public ActorType createActorType() {
        return new ActorType();
    }

    /**
     * Create an instance of {@link Components }
     * 
     */
    public Components createComponents() {
        return new Components();
    }

    /**
     * Create an instance of {@link ConnectionList }
     * 
     */
    public ConnectionList createConnectionList() {
        return new ConnectionList();
    }

    /**
     * Create an instance of {@link PortNameList }
     * 
     */
    public PortNameList createPortNameList() {
        return new PortNameList();
    }

    /**
     * Create an instance of {@link Port }
     * 
     */
    public Port createPort() {
        return new Port();
    }

    /**
     * Create an instance of {@link Actor }
     * 
     */
    public Actor createActor() {
        return new Actor();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link ActorList }
     * 
     */
    public ActorList createActorList() {
        return new ActorList();
    }

    /**
     * Create an instance of {@link ActorTypeList }
     * 
     */
    public ActorTypeList createActorTypeList() {
        return new ActorTypeList();
    }

    /**
     * Create an instance of {@link PortList }
     * 
     */
    public PortList createPortList() {
        return new PortList();
    }

    /**
     * Create an instance of {@link Aggregate}
     * 
     */
    public Aggregate createAggregate() {
        return new Aggregate();
    }

}
